"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR points to the parent directory of settings.py (myproject folder)
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY is used for cryptographic signing and should be kept secret in production
SECRET_KEY = "django-insecure-keo854zatj&e%t1%nfyq+v&zxssm#mm*t#tmxl^l&h2)$y!08#"

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG=True shows detailed error pages; set to False in production
DEBUG = False

# ALLOWED_HOSTS: List of hosts/domains that Django will serve. Empty list allows all in development
ALLOWED_HOSTS = ["*"]


# Application definition
# INSTALLED_APPS: List of all Django apps and third-party apps used in this project
INSTALLED_APPS = [
    "django.contrib.admin",  # Admin interface
    "django.contrib.auth",  # User authentication system
    "django.contrib.contenttypes",  # Content type framework
    "django.contrib.sessions",  # Session management
    "django.contrib.messages",  # Messaging framework for user notifications
    "django.contrib.staticfiles",  # Static files handler (CSS, JS, Images)
    "posts",  # Custom app for blog posts
    "users",  # Custom app for user management
]

# MIDDLEWARE: List of middleware classes that process requests/responses
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",  # Adds security headers
    "django.contrib.sessions.middleware.SessionMiddleware",  # Manages sessions
    "django.middleware.common.CommonMiddleware",  # Handling common tasks
    "django.middleware.csrf.CsrfViewMiddleware",  # CSRF protection
    "django.contrib.auth.middleware.AuthenticationMiddleware",  # Associates users with requests
    "django.contrib.messages.middleware.MessageMiddleware",  # Manages messages
    "django.middleware.clickjacking.XFrameOptionsMiddleware",  # Clickjacking protection
    "django_browser_reload.middleware.BrowserReloadMiddleware",  # Live browser reloading
]

# ROOT_URLCONF: Python path to the root URL configuration module
ROOT_URLCONF = "myproject.urls"

# TEMPLATES: Configuration for template engines
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",  # Django template engine
        "DIRS": [
            "templates",
            "users/templates",
            "posts/templates",
        ],  # Directories where templates are stored
        "APP_DIRS": True,  # Look for templates in app directories
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",  # Adds request to template context
                "django.contrib.auth.context_processors.auth",  # Adds user/auth data to context
                "django.contrib.messages.context_processors.messages",  # Adds messages to context
            ],
        },
    },
]

# WSGI_APPLICATION: Python path to the WSGI application used by Django's runserver
WSGI_APPLICATION = "myproject.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# DATABASES: Configuration for database connections
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",  # SQLite database engine
        "NAME": BASE_DIR / "db.sqlite3",  # Path to SQLite database file
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
# AUTH_PASSWORD_VALIDATORS: Rules that validate user passwords
AUTH_PASSWORD_VALIDATORS = [
    {
        # Prevents passwords that are too similar to user attributes (username, email, etc.)
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        # Ensures passwords meet minimum length requirement
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        # Prevents use of common passwords (e.g., "password123")
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        # Prevents passwords that are entirely numeric
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/
# LANGUAGE_CODE: Default language for this Django installation
LANGUAGE_CODE = "en-us"

# TIME_ZONE: Default timezone for datetime objects
TIME_ZONE = "Asia/Colombo"

# USE_I18N: Enable Django's translation system
USE_I18N = True

# USE_TZ: Use timezone-aware datetimes
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
# STATIC_URL: URL to access static files in the browser (e.g., /static/)
STATIC_URL = "static/"
MEDIA_URL = "media/"
STATIC_ROOT = BASE_DIR / "assests"
MEDIA_ROOT = BASE_DIR / "media"
# STATICFILES_DIRS: List of directories where collectstatic looks for static files
STATICFILES_DIRS = [BASE_DIR, "static"]
